# Generated by Django 4.1.5 on 2023-01-21 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtranslation',
            name='photo',
        ),
    ]
