# Generated by Django 4.1.5 on 2023-01-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0002_remove_blogtranslation_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='photo',
            field=models.ImageField(default='', upload_to='blogs/', verbose_name='Photo'),
            preserve_default=False,
        ),
    ]
